### PR TITLE
Ports Eris Human Sprites

### PR DESCRIPTION
**Pull request by ShibberinoShipperino**
Anatomically better, and less simpsons.

These match the exact same as normal sprites, meaning no clipping will occur.

New:

fa19v7t

Old:

krv7xcq

Fat Sprites are handled differently on Eris, meaning that I will make another PR once I've attempted to stylize the fat torso in a similar fashion. Only two sprites will need to be done.

### CODE REVIEW

**Comment by msgerbs** [comment]
I'm not a huge fan of the dark outline, I think it looks weird especially on the arms. It draws attention to the fact that there is indeed an outline, and that yes, some parts are only a pixel wide. @MrFroztee ?

**Comment by ShibberinoShipperino** [comment]
I find the shading better since it lets you make out things more easier, such as the ears, a more defined body shape, such as the torso pecs and also just general shading. I personally don't take too much issue to the outline though it is quite stand-outy and it shouldnt be too noticeable when clothed.

**Comment by msgerbs** [comment]
The shading is good. Just not sure about the outline being that dark. Could you post a clothed screenshot?

**Comment by MrFroztee** [comment]
I think it's just because they're nude that it looks odd, I'm okay with a more confident pallete.

**Comment by msgerbs** [comment]
Very well.

**Pull request merged**
