### PR TITLE
Updates old Pets/Animals to Current Station Named + New Medibot Lines

### PR DESCRIPTION
**Pull request by ShibberinoShipperino**
- Poly changed to Hephaestus and updated to add more lines to scream.

-Hivebots have had a minor description change.

-Runtime changed to Kirby as by normal cat name in current map Ver.

- Medibot has been updated with new phrases and sounds a lot more glitchy, new visuals coming soon.

- Pun Pun now changed to Plumpers to avoid changing back on round start as Vars seem not to work on him.

### CODE REVIEW

**Comment by msgerbs** [comment]
Conflicts? Did you forget to use the dev branch again?

**Comment by ShibberinoShipperino** [comment]
I'm fairly sure I used the Dev Branch to do it, which is weird.

**Comment by SheepFighter** [comment]
> Poly changed to Hephaestus and updated to add more lines to scream.

What is the point of this?

> Pun Pun now changed to Plumpers to avoid changing back on round start as Vars seem not to work on him.

Ditto. There has to be a better way.

> Medibot has been updated with new phrases and sounds a lot more glitchy, new visuals coming soon.

This is the clincher. It's got some rather nice sound-clips. I'd rather keep them, unless you can come up versions for the new lines.

**Comment by msgerbs** [comment]
I'm with Sheep on this, I don't see the point of these changes, especially the medibot changes.

**Comment by msgerbs** [comment]
Alright so I know why this is conflicting, your branch is from before @SheepFighter ported medibot voices. You've gotta fix that and also add new voice lines. If you PR the name and description changes separately I will happily merge those.

**Comment by ShibberinoShipperino** [comment]
I'm going to redo this with just the name changes.

**Pull request closed without merging**
